### ISSUE TITLE
微信小程序报错，无法正常运行

### ISSUE THREAD

**Issue by p697** [AnnaSearl/examples-anna-remax-ui#1]
![image](https://user-images.githubusercontent.com/51314472/78856167-8d075480-7a58-11ea-8b40-53bdbd1587c5.png)

**Comment by AnnaSearl** [comment]
这个问题看起来是使用了window环境下的API，小程序是不能使用document下的API的

**Comment by p697** [comment]
刚才又打开项目居然一下子正常了，太尴尬了hhh，可能是微信开发者工具的bug

**Comment by AnnaSearl** [comment]
> 刚才又打开项目居然一下子正常了，太尴尬了hhh，可能是微信开发者工具的bug

可以重新拉下代码，有更新了一些组件的示例

**Comment by p697** [comment]
好的，好快啊👍
